Added MyIP( )

diff --git a/trackIP b/trackIP
--- a/trackIP
+++ b/trackIP
@@ -58,3 +58,72 @@ menu (){
     fi
 
 }
+
+myipaddr () {
+    myipaddripapico=$(curl -s "https://ipapi.co//json" -L)
+    myiparrripapicom=$(curl -s "http://ip-api.com/json/" -L)
+    myip=$(echo $myipaddripapico | grep -Po '(?<="ip":)[^,]*' | tr -d '[]"')
+
+    mycity=$(echo $myipaddripapico | grep -Po '(?<="city":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+
+    myregion=$(echo $myipaddripapico | grep -Po '(?<="region":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mycountry=$(echo $myipaddripapico | grep -Po '(?<="country_name":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mylat=$(echo $myipaddripapico | grep -Po '(?<="lat":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mylon=$(echo $myipaddripapico | grep -Po '(?<="lon":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mytime=$(echo $myipaddripapico | grep -Po '(?<="timezone":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mypostal=$(echo $myipaddripapico | grep -Po '(?<="zip":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    myisp=$(echo $myipaddripapico | grep -Po '(?<="org":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    myasn=$(echo $myipaddripapico | grep -Po '(?<="asn":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mycountrycode=$(echo $myipaddripapico | grep -Po '(?<="country_code":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mycurrency=$(echo $myipaddripapico | grep -Po '(?<="currency":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mylanguage=$(echo $myipaddripapico | grep -Po '(?<="languages":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+    mycalling=$(echo $myipaddripapico | grep -Po '(?<="country_calling_code":)[^,]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+
+banner
+
+    printf "\e[0m\n"
+    printf "\e[0\n"
+    printf "  \e[0m\e[1;93m  Ip Address    \e[0m\e[1;96m:\e[0m\e[1;92m   $myip\e[0m\n"
+    printf "  \e[0m\e[1;93m  City          \e[0m\e[1;96m:\e[0m\e[1;92m   $mycity\e[0m\n"
+    printf "  \e[0m\e[1;93m  Region        \e[0m\e[1;96m:\e[0m\e[1;92m   $myregion\e[0m\n"
+    printf "  \e[0m\e[1;93m  Country       \e[0m\e[1;96m:\e[0m\e[1;92m   $mycountry\e[0m\n"
+    printf "\e[0m\n"
+    printf "  \e[0m\e[1;93m  Latitude      \e[0m\e[1;96m:\e[0m\e[1;92m    $mylat\e[0m\n"
+    printf "  \e[0m\e[1;93m  Longitude     \e[0m\e[1;96m:\e[0m\e[1;92m    $mylon\e[0m\n"
+    printf "  \e[0m\e[1;93m  Time Zone     \e[0m\e[1;96m:\e[0m\e[1;92m    $mytime\e[0m\n"
+    printf "  \e[0m\e[1;93m  Postal Code   \e[0m\e[1;96m:\e[0m\e[1;92m    $mypostal\e[0m\n"
+    printf "\e[0m\n"
+    printf "  \e[0m\e[1;93m  ISP           \e[0m\e[1;96m:\e[0m\e[1;92m   $myisp\e[0m\n"
+    printf "  \e[0m\e[1;93m  ASN           \e[0m\e[1;96m:\e[0m\e[1;92m   $myasn\e[0m\n"
+    printf "\e[0m\n"
+    printf "  \e[0m\e[1;93m  Country Code  \e[0m\e[1;96m:\e[0m\e[1;92m   $mycountrycode\e[0m\n"
+    printf "  \e[0m\e[1;93m  Currency      \e[0m\e[1;96m:\e[0m\e[1;92m   $mycurrency\e[0m\n"
+    printf "  \e[0m\e[1;93m  Languages     \e[0m\e[1;96m:\e[0m\e[1;92m   $mylanguage\e[0m\n"
+    printf "  \e[0m\e[1;93m  Calling Code  \e[0m\e[1;96m:\e[0m\e[1;92m   $mycalling\e[0m\n"
+    printf "\e[0m\n"
+    printf "  \e[0m\e[1;93m  GOOGLE Maps   \e[0m\e[1;96m:\e[0m\e[1;94m  https://maps.google.com/?q=$mylat,$mylon\e[0m\n"
+
+    sleep 2.5 
+
+    printf "\e[0m\n"
+    printf "  \e[0m\e[1;91m[\e[0m\e[1;97m01\e[0m\e[1;91m]\e[0m\e[1;93m Return To Main Menu\e[0m\n"
+    printf "  \e[0m\e[1;91m[\e[0m\e[1;97m02\e[0m\e[1;91m]\e[0m\e[1;93m Exit\e[0m\n"
+    printf "\e[0m\n"
+    read -p $'  \e[1;31m>>\e[0m\e[1;96m  \en' mainorexit1
+
+    if [[ $mainorexit1 == 1 || $mainorexit1 == 01 ]]
+    then
+        banner
+        menu
+    elif [[ $mainorexit1 == 2 || $mainorexit1 == 02 ]]; then
+        printf "\e[0m\n"
+        printf "\e[0m\n"
+        exit 1
+    else
+        printf " \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
+        sleep 1
+        banner
+        menu
+    fi
+
+}
